"""Initial migration with wallet system

Revision ID: 119205bd7341
Revises: 
Create Date: 2026-01-01 21:48:40.093117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119205bd7341'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disbursed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_repaid', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('is_fully_repaid', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_requests', schema=None) as batch_op:
        batch_op.drop_column('is_fully_repaid')
        batch_op.drop_column('total_repaid')
        batch_op.drop_column('disbursed_at')
        batch_op.drop_column('approved_amount')

    # ### end Alembic commands ###
